version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://mongo:27017
    depends_on:
      - mongo
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
